image: node:14.15.1-buster

before_script:
  - echo "Job `$CI_JOB_NAME` started."

after_script:
  - echo "Job `$CI_JOB_NAME` ended."

stages:
  - build
  - staging
  - production

build:
  type: build
  script:
    - npm install
    - npm run build
  except:
    - master
    - development

deploy-staging:
  type: deploy
  stage: staging
  only:
    - development
  environment:
    name: staging
    url: https://staging-sayurhub.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby ruby-dev rubygems-integration
    - gem install dpl
    - dpl --provider=heroku --app=staging-sayurhub --api-key=$HEROKU_API_KEY

deploy-production:
  type: deploy
  stage: production
  environment:
    name: production
    url: https://sayurhub.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby ruby-dev rubygems-integration
    - gem install dpl
    - dpl --provider=heroku --app=sayurhub --api-key=$HEROKU_API_KEY
  only:
    - master
